server {
    listen 8080;
    server_name "";
    access_log off;
    error_log  /dev/stdout info;

    location / {
      root /var/www/data/;
    }

    location /healthz {
      return 200 "Healthy";
    }

    location / {
      root /var/www/static/;
    }
}